# Generated by Django 5.1.3 on 2024-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELEC', 'Electronics'), ('FASH', 'Fashion'), ('KITCH', 'Home & Kitchen'), ('BOOKS', 'Books')], max_length=20)),
                ('image', models.FileField(upload_to='categories/')),
            ],
        ),
    ]
