# Generated by Django 5.1.3 on 2024-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_index_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_products',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home & Kitchen'), ('Books', 'Books')], max_length=20),
        ),
    ]
