# Generated by Django 5.1.3 on 2024-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_index_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home & Kitchen'), ('Books', 'Books')], max_length=20)),
                ('image', models.FileField(upload_to='featured/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
