# Generated by Django 5.1.3 on 2024-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_user_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
