# Generated by Django 5.1.3 on 2024-11-19 17:02

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_user_profile_address_alter_user_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books', 'Books'), ('Home', 'Home & Kitchen')], max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.FileField(upload_to=App.models.get_upload_to)),
                ('stock_quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
