# Generated by Django 5.1.3 on 2024-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_products_upload_datetime_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers_Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='offers-deals/')),
                ('desciption', models.TextField(max_length=300)),
            ],
        ),
    ]
