# Generated by Django 5.1.3 on 2024-11-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_offers_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers_deals',
            old_name='desciption',
            new_name='description',
        ),
    ]
