# Generated by Django 5.1.3 on 2024-12-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_bidmodel_delete_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_chats',
            name='receiver',
        ),
    ]
